---
title: "CONJ 620: Grades"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: flatly
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(DT)
library(wesanderson)
sakai <- read_csv(here::here("data", "sakai.csv"),
                  na = "No Submission")
dc <- read_csv(here::here("data", "dc.csv"))
```

Labs
===================================== 

Most recent update: 2018-09-25

Column {data-width=650}
-----------------------------------------------------------------------

### Labs (non-integrative)

Note: The 3 lowest labs grades have been dropped, and a curve was applied such that a "check" on all 11 labs resulted in a grade of 90.

```{r}
int_labs <- c("lab_06a", "lab_06b", 
              "lab_11a", "lab_11b", 
              "lab_15a", "lab_15b",
              "lab_19a", "lab_19b")

labs <- sakai %>% 
  filter(!lab %in% int_labs)

# there are 14 labs
total_labs <- labs %>% 
  distinct(lab) %>% 
  tally() %>% 
  pull()

# drop 3 lowest
labs_to_grade <- total_labs - 3
labs_keep <- labs %>% 
  arrange(fake_name, desc(grade)) %>% 
  group_by(fake_name) %>% 
  top_n(labs_to_grade, grade) %>% 
  filter(row_number() %in% c(1:labs_to_grade)) %>% 
  ungroup()

# check this
# should be 11 each
#labs_keep %>% 
#  count(fake_name, sort = TRUE)

# make sums
# I want:
# a x0 = 22 --> y0 = 90
# a x1 = 30 --> y1 = 100
# 33 is max possible, but 30 is max in data
lab_sums <- labs_keep %>% 
  group_by(fake_name) %>% 
  summarize(lab_grades = ceiling(90 + 1.25 * (sum(grade) - 22)))

lab_grades <- labs_keep %>% 
  count(fake_name, grade) %>% 
  spread(grade, n, fill = 0) %>% 
  select(fake_name, check_plus = `3`, check = `2`, 
         check_minus = `1`, miss_late = `0`) %>% 
  mutate(adj_plus = ifelse(check_plus - check_minus > 0, 
                           check_plus - check_minus,
                           0),
         adj_check = check + 2*(check_plus - adj_plus) + adj_plus,
         adj_minus = ifelse(check_minus - check_plus >= 0, 
                           check_minus - check_plus,
                           0),
         adj_ratio = ceiling(adj_check / adj_minus),
         adj_bounce = 2*floor((adj_plus / adj_check)*total_labs)) %>% 
  mutate(lab_grade = case_when(
    # pluses
    adj_plus == floor(.2*labs_to_grade) & 
      adj_check == labs_to_grade ~ 92,
    adj_plus == floor(.3*labs_to_grade) & 
      adj_check == labs_to_grade ~ 96,
    adj_plus >= floor(.4*labs_to_grade) & 
      adj_check == labs_to_grade ~ 100,
    # solid = A
    adj_check == labs_to_grade ~ 90,
    between(adj_check, floor(.8*labs_to_grade), ceiling(.8*labs_to_grade)) ~ 80 + adj_bounce,
    between(adj_check, floor(.7*labs_to_grade), ceiling(.7*labs_to_grade)) ~ 75 + adj_bounce,
    between(adj_check, floor(.6*labs_to_grade), ceiling(.6*labs_to_grade)) ~ 70 + adj_bounce,
    adj_check < floor(.6*labs_to_grade) ~ 65 + adj_bounce,
    # if minuses remain
    adj_plus == 0 & adj_ratio >= 4 ~ 80,
    adj_plus == 0 & between(adj_ratio, 3, 3.9) ~ 75,
    adj_plus == 0 & between(adj_ratio, 2, 2.9) ~ 70,
    adj_plus == 0 & between(adj_ratio, 1, 1.9) ~ 65
  )) %>% 
  left_join(lab_sums) %>% 
  select(-starts_with("adj_"), -lab_grade) %>% 
  identity()
  
lab_grades %>% 
  datatable(rownames = FALSE,
            class = 'cell-border stripe',
            filter = list(position = 'top'),
            options = list(pageLength = nrow(lab_grades), 
                           autoWidth = TRUE,
                           bInfo = FALSE,
                           paging = FALSE),
            escape = FALSE)
```
  


Column {data-width=350}
-----------------------------------------------------------------------

### Grades by lab (raw)

```{r}
labs %>% 
  filter(!grade == 0) %>% 
  ggplot(., aes(x = lab, fill = as.factor(grade))) +
  geom_bar(position = "fill") +
  scale_fill_manual(values = wes_palette("Royal2")[c(5:3)], 
                    name = "",
                    labels=c("minus", "check", "plus")) +
  labs(x = "", y = "percent of students") + 
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  theme(legend.position="bottom",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

### Overall lab grades

```{r}
ggplot(lab_grades, aes(x = lab_grades)) +
  geom_histogram(colour = "white", binwidth = 3, fill = wes_palette("Royal2")[5]) +
  labs(x = "overall grade on lab portion") +
  theme_minimal() 
```



Integrative Labs
===================================== 

Column {data-width=650}
-----------------------------------------------------------------------

### Integrative Labs

There were four of these total, each worth 5 points (2 pts for initial submission; 3 for self-assessment). A curve of 5 percentage pts was added to the final % score.

```{r}
# 5 int labs
int_labs <- c("lab_06a", "lab_06b", 
              "lab_11a", "lab_11b", 
              "lab_15a", "lab_15b",
              "lab_19a", "lab_19b")

ilabs <- sakai %>% 
  filter(lab %in% int_labs) %>% 
  mutate(lab_num = parse_number(lab)) %>% 
  group_by(fake_name, lab_num) %>% 
  summarize(ilab_grade = sum(grade)) %>% 
  ungroup() %>% 
  mutate(ilab_grade = if_else(lab_num == 19 & fake_name == "clever-neumann", 
         0, ilab_grade)) %>% 
  mutate(ilab_grade = if_else(lab_num == 15 & fake_name == "vigorous-chandrasekhar", 
         5, ilab_grade))

ilabs_grades <- ilabs %>% 
  group_by(fake_name) %>% 
  summarize(ilab_sum = sum(ilab_grade)) %>% 
  mutate(ilab_sum = if_else(fake_name == "cocky-keller", ilab_sum + 5, ilab_sum)) %>% 
  mutate(ilab_prop = (ilab_sum / 20) * 100) %>% 
  mutate(ilab_curved = ilab_prop + 5)

ilabs_grades %>% 
  datatable(rownames = FALSE,
            class = 'cell-border stripe',
            filter = list(position = 'top'),
            options = list(pageLength = nrow(ilabs), 
                           autoWidth = TRUE,
                           bInfo = FALSE,
                           paging = FALSE),
            escape = FALSE)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Grades for each integrative lab (n = 4)

```{r}
ilabs %>% 
  filter(!ilab_grade == 0) %>% 
  ggplot(., aes(x = as.factor(lab_num), fill = as.factor(ilab_grade))) +
  geom_bar(position = "fill") +
  scale_fill_manual(values = wes_palette("Royal2")[c(5:1)], 
                    name = "") +
  labs(x = "", y = "percent of students") + 
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  theme(legend.position="bottom",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

### Overall integrative lab grades (curved)

```{r}
ggplot(ilabs_grades, aes(x = ilab_curved)) +
  geom_histogram(colour = "white", binwidth = 3, fill = wes_palette("Royal2")[5]) +
  labs(x = "") +
  theme_minimal() 
```


DataCamp
=====================================  


### DataCamp Courses Completed

```{r}
dc_out_of <- dc %>% 
  distinct(course) %>% 
  tally() %>% 
  pull()

# 80% of assignments on time get an A
# so far, all courses have had 4 chapters
dc_grades <- dc %>% 
  count(fake_name, wt = completed) %>% 
  mutate(prop = round(n / dc_out_of, 2),
         dc_grade = case_when(
           between(prop, .9, 1) ~ 100,
           between(prop, .8, .89) ~ 90,
           between(prop, .7, .79) ~ 70,
           TRUE ~ 60
         ))

dc_grades %>% 
  datatable(rownames = FALSE,
            class = 'cell-border stripe',
            filter = list(position = 'top'),
            options = list(pageLength = nrow(dc), 
                           #autoWidth = TRUE,
                           bInfo = FALSE,
                           paging = FALSE),
            escape = FALSE)
```

Final Grades
=====================================  


Column {data-width=650}
-----------------------------------------------------------------------

### Weighted combined final grades

```{r}
combined <- lab_grades %>% 
  left_join(ilabs_grades) %>% 
  left_join(dc_grades) %>% 
  select(fake_name, lab_grades, ilab_curved, dc_grade) %>% 
  mutate(final = ceiling((.4 * lab_grades) +
           (.4 * dc_grade) +
           (.2 * ilab_curved)))

combined %>% 
  datatable(rownames = FALSE,
            class = 'cell-border stripe',
            filter = list(position = 'top'),
            options = list(pageLength = nrow(combined), 
                           #autoWidth = TRUE,
                           bInfo = FALSE,
                           paging = FALSE),
            escape = FALSE)
```


Column {data-width=350}
-----------------------------------------------------------------------


### Final combined grades

```{r}
ggplot(combined, aes(x = final)) +
  geom_histogram(colour = "white", binwidth = 5, fill = wes_palette("Royal2")[5]) +
  labs(x = "") +
  theme_minimal() 
```

```{r echo = FALSE}
# export final grades
names <- read_csv("/Users/hillali/Box Sync/CONJ 620 Grades/name_key.csv")
combined <- combined %>% 
  left_join(names) %>% 
  mutate(final_grade = case_when(
    final >= 98 ~ "A+",
    final >= 90 ~ "A",
    final >= 88 ~ "B+",
    final >= 80 ~ "B",
    final >= 82 ~ "B-",
    final >= 70 ~ "C",
    is.na(final) ~ "I"
  )) %>% 
  select(name, final_grade, final)
write_csv(combined, "final_grades.csv")
```

